# -*- coding: utf-8 -*-
"""Temporary helper: replace Chinese phrases with English in experiments/*.py.
Applied to comments/docstrings/print strings only in spirit; code identifiers are untouched.
Delete after use."""
import os

EXP_ROOT = r"F:\个人\HF\交通预测\reproducible_uc"

PHRASES = [
    # ---- sentence/docstring level ----
    ("R3 四段 canonical 评估（Round1 审计修复后主表）。", "R3 four-split canonical evaluation (post Round1-audit-fix main table)."),
    ("R3 four-split canonical evaluation (post Round1-audit fix main table).", "R3 four-split canonical evaluation (post Round1-audit-fix main table)."),
    ("protocol（与 train_r3.py 完全一致）：", "Protocol (identical to train_r3.py):"),
    ("四段边界：train=int(T*0.6) / select=int(T*0.7) / calib=int(T*0.8) / test=T", "four-split boundaries: train=int(T*0.6) / select=int(T*0.7) / calib=int(T*0.8) / test=T"),
    ("窗口起点 g 半开范围 [start, end-24)（窗口输出末点 ≤ end-1）", "window start g in half-open range [start, end-24) (window output end point <= end-1)"),
    ("calib 起点 = select_end（训练 select 末 g=select_end-24 → 隐含 purge 23 anchors，P1-6 满足）", "calib start = select_end (train select last g = select_end-24 -> implicitly purges 23 anchors, satisfies P1-6)"),
    ("canonical taxonomy（12 步错位修正 + zero mask）+ 统一 severity（Q99 clip）+ hard-bin 主方法", "canonical taxonomy (12-step misalignment fix + zero mask) + unified severity (Q99 clip) + hard-bin main method"),
    ("valid mask (true>0) 贯穿 coverage/WCE/GCD", "valid mask (true>0) threaded through coverage/WCE/GCD"),
    ("α=0.10；输出 WCE/WCE_group/GCD/q_monotonic/per-group width + interp 变体", "alpha=0.10; outputs WCE/WCE_group/GCD/q_monotonic/per-group width + interp variant"),
    ("R3 等价验收 (Gate): train_r3 transform 管线 vs official protocol (ucg1/c2_sweep inference chain).",
     "R3 equivalence acceptance (Gate): train_r3 transform pipeline vs official protocol (ucg1/c2_sweep inference chain)."),
    ("R3 equivalence acceptance (Gate): train_r3 transform 管线 vs official protocol (ucg1/c2_sweep inference chain).",
     "R3 equivalence acceptance (Gate): train_r3 transform pipeline vs official protocol (ucg1/c2_sweep inference chain)."),
    ("R4: window-level paired stationary bootstrap method-effect CI (P0-7 correct implementation).",
     "R4: window-level paired stationary bootstrap method-effect CI (P0-7 correct implementation)."),
    ("P1-9: normalized conformal into R3/R4 main table (Round1 audit P1-9 fix).",
     "P1-9: normalized conformal into R3/R4 main table (Round1 audit P1-9 fix)."),
    ("P1-7 + P1-8: node-window granularity rho and flow-stratified bootstrap (fixed version).",
     "P1-7 + P1-8: node-window granularity rho and flow-stratified bootstrap (fixed version)."),
    ("R3 training: STAEformer scratch four-split (Round1 audit P0-1 fixed version).",
     "R3 training: STAEformer scratch four-split (Round1 audit P0-1 fixed version)."),
    ("UC-G3b: STID x PEMS04 training (legacy framework, four-split, fast_val + early stop).",
     "UC-G3b: STID x PEMS04 training (legacy framework, four-split, fast_val + early stop)."),
    ("UC-G3b: STAEformer x PEMS03/07 training (scratch, dataset generalization).",
     "UC-G3b: STAEformer x PEMS03/07 training (scratch, dataset generalization)."),
    ("UC-G3b: STAEformer x PEMS07 training (Fast Validation + four-split + early stopping).",
     "UC-G3b: STAEformer x PEMS07 training (Fast Validation + four-split + early stopping)."),
    # ---- common fragment level ----
    ("四段", "four-split"),
    ("主表", "main table"),
    ("（Round1 审计修复后", "(post Round1-audit fix"),
    ("完全一致", "identical"),
    ("半开范围", "half-open range"),
    ("窗口输出末点", "window output end point"),
    ("隐含 purge", "implicit purge"),
    ("满足", "satisfied"),
    ("错位修正", "misalignment fix"),
    ("统一", "unified"),
    ("主方法", "main method"),
    ("贯穿", "threaded through"),
    ("变体", "variant"),
    ("等价验收", "equivalence acceptance"),
    ("管线", "pipeline"),
    ("预训练", "pretrained"),
    ("空间训练", "space training"),
    ("前 128 窗", "first 128 windows"),
    ("同窗对比", "window-by-window comparison"),
    ("重训放行", "retraining cleared"),
    ("正确实现", "correct implementation"),
    ("窗口级", "window-level"),
    ("方法效应", "method-effect"),
    ("审计", "audit"),
    ("重采样单位", "resampling unit"),
    ("时间结构保留", "temporal structure preserved"),
    ("每 replicate", "per replicate"),
    ("重算", "recompute"),
    ("抽样", "sampling"),
    ("降采样", "downsampling"),
    ("丢失时间块", "losing time blocks"),
    ("敏感性", "sensitivity"),
    ("汇总", "summary"),
    ("样本 SD", "sample SD"),
    ("修复点", "fix"),
    ("scale 函数", "scale function"),
    ("从 select 段估", "estimated from select split"),
    ("非 calib", "not calib"),
    ("test 只评价", "test only evaluated"),
    ("固定", "fixed"),
    ("无 select 段预测可用", "no select-split prediction available"),
    ("用 train 段模型输出不可行", "using train-split model output is infeasible"),
    ("替代方案", "alternative"),
    ("保持 split-conformal 精神", "keeping the split-conformal spirit"),
    ("校准 q 用", "calibration q uses"),
    ("或直接报告", "or report directly"),
    ("作为对照", "as a control"),
    ("同源", "same-source"),
    ("已标注局限", "limitation noted"),
    ("与旧版一致", "consistent with the old version"),
    ("本实现采用", "this implementation adopts"),
    ("仅更新到", "only updated to"),
    ("node-window 粒度", "node-window granularity"),
    ("压缩", "compression"),
    ("生态相关", "ecological correlation"),
    ("现按", "now per"),
    ("先 node 内去均值", "first demean within node"),
    ("再做时间 block", "then time-block"),
    ("flow-stratified bootstrap 修复", "flow-stratified bootstrap fix"),
    ("先重采样 window block", "first resample window block"),
    ("再在 replicate 内", "then within replicate"),
    ("三分位", "terciles"),
    ("各报 CI", "report CI each"),
    ("修复旧版", "fixes the old version"),
    ("先筛后重采样致破坏时序", "filter-then-resample broke temporal order"),
    ("的 bug", " bug"),
    ("正确接入", "correctly wired"),
    ("显式", "explicitly"),
    ("同口径", "same convention"),
    ("改", "changed to"),
    ("严格", "strictly"),
    ("不越界进 calib", "does not cross into calib"),
    ("与 eval 统一", "unified with eval"),
    ("起", "onward"),
    ("错标", "mislabeled"),
    ("下", "under"),
    ("旧 raw 输入下", "under old raw-input"),
    ("实为", "was actually"),
    ("与官方 val 可比", "comparable to official val"),
    ("训练快", "training is fast"),
    ("纯 MLP", "pure MLP"),
    ("预切", "pre-split"),
    ("后半作 calib", "second half as calib"),
    ("训练时 select 用", "training-time select uses"),
    ("验证数据集泛化", "verify dataset generalization"),
    ("对齐官方", "aligned with the official"),
    ("无 AMP", "no AMP"),
    ("官方", "official"),
    ("配置", "config"),
    ("Fast Validation", "Fast Validation"),
    ("只算", "only compute"),
    ("归一化空间", "norm space"),
    ("checkpoint selection 用", "used for checkpoint selection"),
    ("省 RMSE/MAPE/inverse_transform", "skips RMSE/MAPE/inverse_transform"),
    ("val 频率", "val frequency"),
    ("每 5 epoch 一次", "every 5 epochs"),
    ("每 10 epoch", "every 10 epochs"),
    ("batch 16", "batch 16"),
    ("数据加载加速", "load acceleration"),
    ("num_workers 致 GPU 空闲等待", "num_workers causes GPU idle wait"),
    ("用法:", "Usage:"),
    ("返回", "returns"),
    ("训练", "training"),
    ("测试", "test"),
    ("数据", "data"),
    ("推理", "inference"),
    ("模型", "model"),
    ("窗口", "window"),
    ("标签", "labels"),
    ("节点", "node"),
    ("差分", "diff"),
    ("统计", "stats"),
    ("参数", "parameters"),
    ("初始化", "initialization"),
    ("优化", "optimizer"),
    ("加权", "weighted"),
    ("日志", "log"),
    ("曲线", "curve"),
    ("修复", "fix"),
    ("段", "split"),
    ("池化", "pooled"),
    ("计数", "counts"),
    ("责任组", "responsible group"),
    ("计算", "compute"),
    ("可", "can"),
    ("同", "same"),
    ("与", "and"),
    ("和", "and"),
    ("在", "on"),
    ("上", "on"),
    ("内", "within"),
    ("外", "outside"),
    ("不", "not"),
    ("无", "no"),
    ("有", "has"),
    ("被", "is"),
    ("为", "is"),
    ("用", "use"),
    ("从", "from"),
    ("到", "to"),
    ("至", "to"),
    ("后", "after"),
    ("前", "before"),
    ("各", "each"),
    ("按", "by"),
    ("每", "per"),
    ("仅", "only"),
    ("均", "all"),
    ("即", "i.e."),
    ("故", "thus"),
    ("若", "if"),
    ("则", "then"),
    ("含", "incl."),
    ("：", ": "),
    ("；", "; "),
    ("（", " ("),
    ("）", ")"),
    ("，", ", "),
    ("。", ". "),
    ("、", ", "),
    ("——", " -- "),
    ("→", " -> "),
    ("≥", ">="),
    ("≤", "<="),
    ("×", "x"),
    ("±", "+/-"),
    ("≈", "~"),
    ("⌈", "ceil("),
    ("⌉", ")"),
    ("−", "-"),
    ("ŷ", "yhat"),
    ("Δ", "delta"),
    ("α", "alpha"),
    ("λ", "lambda"),
    ("ρ", "rho"),
    ("Σ", "sum "),
    ("∈", "in "),
]

def translate_line(line):
    out = line
    for cn, en in PHRASES:
        if cn in out:
            out = out.replace(cn, en)
    return out

count = 0
for r, _, fs in os.walk(os.path.join(EXP_ROOT, 'experiments')):
    for fn in fs:
        if not fn.endswith('.py'):
            continue
        p = os.path.join(r, fn)
        lines = open(p, encoding='utf-8').read().split('\n')
        newlines = [translate_line(l) for l in lines]
        if newlines != lines:
            open(p, 'w', encoding='utf-8').write('\n'.join(newlines))
            count += 1
            print('translated:', os.path.relpath(p, EXP_ROOT))
print('done, files changed:', count)
