# -*- coding: utf-8 -*-
"""PR2：将收件包（UC_condensed_revision，8 页主稿 + 8 页补充材料）的 15 张表改为生成表。

背景：外部审查者交来的精简稿里 15 张表的数字是手打的。本脚本把这些表格环境
逐字重建成 `results/**.json -> 生成器 -> paper/condensed/generated/*.tex -> \\input`
通道，**一个渲染数字都不允许改变**（--check 逐字节比对环境本体）。

表格数字的唯一来源（映射关系已由 scripts/pr2_verify_package.py 逐格证明，
1,646 个转录格零数值不一致）：
  results/phase2_E7/v1/<config>.json        metrics[prog].V1: path_cov / mean_width / IS /
                                            n_paths / group_path_cov  —— tab:cost, tab:copula,
                                            tab:severity, tab:rules
  results/phase3_PR1/pr1_supplementary.json configs[cfg]: identity（tab:pop, tab:events,
                                            tab:forecast, tab:data 的计数与点预测质量）、
                                            support_clip（tab:support）、
                                            prospective_paths（tab:cells, tab:prospective,
                                            tab:cellcounts）、
                                            effect_sizes（tab:effects, tab:severity/rules 的比值列）
  results/phase3_PR1/pr1_dataset_identity.json  tab:data 的 Nodes / Time steps
  results/phase1_R1/c4_decision_proxy_v2.json   tab:decision（3 种子子组均值）
  results/phase1_R1/p08_copulacpts_v2.json      tab:copula 的两个 Copula 变体
  results/phase2_E7/author_finding_checks.json  tab:sweep 的斜率符号计数与示例 ΔC
  results/phase2_E7/cross_config_C3.json        tab:sweep 的 L4_by_dataset.drift_mean 尺度比
  results/phase0_probes/d3_oracle.json / results/phase1_R1/e1_appendix_recomputed.json /
  results/phase2_E7/e4_artifacts.json 只支撑正文散文数字（表头注释按交付约定列出全部来源）。

口径要点（与 pr2_verify_package.py 一致，不得改写）：
  * 表内效应列取 effect_sizes 的**点估计**，不取 contrasts 的自举均值；
  * TypeB/TypeC 的组级覆盖效应取 v1 metrics 的 group_path_cov，逐种子求差再对 3 种子平均；
  * tab:support / tab:decision / tab:cells 的绝对宽度是配置内先算再跨配置平均的量；
  * tab:prospective 的 min--max 定义与 scripts/gen_tables_pr1.py::_span 相同
    （先对三种子逐格取均值，再在六格维度上取 min/max），本脚本直接复用该定义；
  * 计数列（tab:cellcounts）只用 seed 42。

生成的文件与环境本体逐字节一致；两行表头注释是唯一允许多出的内容。

工作副本 paper/condensed/ 的内容与搬运说明：
  * main.tex / supplement.tex —— 收件包手稿逐字复制，仅把 15 个
    \\begin{tabular}/\\begin{longtable} ... \\end{...} 环境各替换为一行
    \\input{generated/tab_<name>}；其余字节完全相同（含收件包 supplement.tex
    第 163 行 caption 里那枚 \\t 制表符：那是原稿把 \\textquotesingle 打成 TAB+
    "extquotesingle" 的既有笔误，位于环境之外，按"逐字节相同"要求原样保留）。
  * references.bib —— 从 manuscript/ 原样复制，主稿 \\bibliography{references} 需要。
  * main.bbl —— 原样复制，使只跑两遍 pdflatex（不调 bibtex）也能出完整参考文献表。
  * 未复制其他文件：两份源都只 usepackage 通用包（geometry/fontenc/lmodern/microtype/
    amsmath/amssymb/booktabs/array/tabularx/longtable/natbib/hyperref/enumitem/caption），
    收件包目录里没有 .cls/.sty，两份源全文也没有一条 \\includegraphics（无插图），
    所以 paper/condensed/ 不需要 figures 目录，也不需要改任何图形路径。

用法：
  python scripts/gen_tables_pr2.py               # 写入 paper/condensed/
  python scripts/gen_tables_pr2.py --check        # 只校验，不写任何文件
  python scripts/gen_tables_pr2.py --out <dir>    # 只把 15 张生成表写到 <dir>/generated/
                                                  # （PR3 合并稿基线 paper/integrated 用；
                                                  #  不写工作副本 tex，不复制 bib/bbl，
                                                  #  --check 的比对口径不受影响）
"""
import argparse
import glob
import json
import os
import re
import shutil
import sys
import tempfile

import numpy as np

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG = os.path.join(ROOT, 'plan', 'reviews', '20260923_r2', 'UC_condensed_revision')
OUT = os.path.join(ROOT, 'paper', 'condensed')
GEN = os.path.join(OUT, 'generated')
V1D = os.path.join(ROOT, 'results', 'phase2_E7', 'v1')

# ---- 对收件包的两处**已登记**偏离（其余 14 表与全部正文逐字节相同）------------
# (1) tab:cells 末列（complementary flow grouping 的 range）：收件包 20 行里有 6 行
#     取的是"种子 × 六格共 18 个格值直接取 min/max"（更宽），与本表其余列（三种子
#     均值）以及 62 页稿 table_prospective_path.tex 的同一列都不是同一个统计量。
#     这里统一为"先按种子平均、再在六格上取极值"（= gen_tables_pr1::_span 口径），
#     与主稿 tab:prospective 一致。勘误 E-24-16。
FLOW_RANGE = 'seed_mean'          # 'pooled' 可逐字节复现收件包原值
KNOWN_DEV = {'tab:cells'} if FLOW_RANGE == 'seed_mean' else set()
# (2) 收件包排版缺陷：pandoc 把表 S6 题注里的右单引号写成 TAB + "extquotesingle"，
#     收到的 PDF 里真的印成 "seed extquotesingle s complete test population"。
#     这是文字不是数字，按投稿要求修好；反向比对时先还原，仍证明"除登记项外零改动"。
TEXT_FIXES = [('seed\textquotesingle s', "seed's")]

HDR = ("% AUTO-GENERATED by scripts/gen_tables_pr2.py -- DO NOT EDIT BY HAND.\n"
       "% Sources: results/phase2_E7/v1/, results/phase3_PR1/pr1_supplementary.json, "
       "results/phase1_R1/{c4_decision_proxy_v2,p08_copulacpts_v2,e1_appendix_recomputed}.json, "
       "results/phase0_probes/d3_oracle.json, "
       "results/phase2_E7/{e4_artifacts,cross_config_C3,author_finding_checks}.json")

SRC = {'main': os.path.join(PKG, 'manuscript', 'main.tex'),
       'supp': os.path.join(PKG, 'supplement', 'supplement.tex')}

SUBS = ['PEMS03_stae', 'PEMS04_stae', 'PEMS08_stae', 'PEMS08_stid']
SLAB = {'PEMS03_stae': 'P03/A', 'PEMS04_stae': 'P04/A',
        'PEMS08_stae': 'P08/A', 'PEMS08_stid': 'P08/I'}
NET = {'PEMS03_stae': 'PeMS03', 'PEMS04_stae': 'PeMS04',
       'PEMS08_stae': 'PeMS08', 'PEMS08_stid': 'PeMS08'}
DSNAME = {'PEMS03_stae': 'PEMS03', 'PEMS04_stae': 'PEMS04',
          'PEMS08_stae': 'PEMS08', 'PEMS08_stid': 'PEMS08'}
SHORTNET = {'PEMS03_stae': 'P03', 'PEMS04_stae': 'P04',
            'PEMS08_stae': 'P08', 'PEMS08_stid': 'P08'}
SEEDS = [42, 123, 456]
CELLS = ['hi0_t0', 'hi0_t1', 'hi0_t2', 'hi1_t0', 'hi1_t1', 'hi1_t2']

# 表内程序显示名 -> 产物里的程序键
PROG_COST = [('Pointwise', 'uncond'), ('Path maximum', 'path_global'),
             ('Bonferroni', 'bonferroni_aH'), ('NH', 'nh_path'),
             (r'Learned $g_0$', 'g0'), (r'Learned $g_1$', 'g1')]
PROG_CELL = [('Pointwise', 'uncond'), ('Path max.', 'path_global'), ('NH', 'nh_path'),
             ('g0', 'g0'), ('g1', 'g1')]
PROG_SUPP = [('Pointwise', 'uncond'), ('Severity Mondrian', 'sev'),
             ('Flow Mondrian', 'flow'), ('Predicted-magnitude Mondrian', 'pmag'),
             ('NH element', 'nh_elem'), ('NH path', 'nh_path'),
             ('Path maximum', 'path_global'), ('Bonferroni', 'bonferroni_aH'),
             ('Learned g0', 'g0'), ('Learned g1', 'g1')]
PROG_PROSP = [('Path maximum', 'path_global'), ('NH', 'nh_path'),
              (r'$g_0$', 'g0'), (r'$g_1$', 'g1')]
CONTRASTS = [('g1/g0', 'g1__vs__g0'), ('g1/path', 'g1__vs__path_global'),
             ('NH/path', 'nh_path__vs__path_global')]
DEC_PROG = [('Pointwise', 'uncond'), ('g1', 'g1'),
            ('Step-upper', 'stepwise_upper'), ('Peak', 'peak_true')]
DEC_GROUPS = ['PEMS04_stae', 'PEMS03_stae', 'PEMS08_stae', 'PEMS08_stid']
COP_PROG = [('Path', 'path_global', None), ('NH', 'nh_path', None), ('g0', 'g0', None),
            ('Copula', None, 'P08a_copulacpts_native'),
            ('Copula+NH', None, 'P08b_copulacpts_nh_adapted')]
COP_ROWS = [('PEMS04_stae', 42), ('PEMS04_stae', 123), ('PEMS04_stae', 456),
            ('PEMS03_stae', 42)]
SWEEP_ROWS = [('PEMS04_stae', 'g0_base', 'g0'), ('PEMS04_stae', 'g1_base_plus_severity', 'g1'),
              ('PEMS03_stae', 'g0_base', 'g0'), ('PEMS03_stae', 'g1_base_plus_severity', 'g1'),
              ('PEMS08_stae', 'g0_base', 'g0'), ('PEMS08_stae', 'g1_base_plus_severity', 'g1')]


# ------------------------------------------------------------------ formatting
def fx(x, dp):
    """定点格式化（与收件包显示的舍入约定一致）。"""
    return '%.*f' % (dp, float(x))


def lead(x, dp):
    """去掉个位零的写法：0.5717 -> .5717，1.004 -> 1.004。"""
    s = fx(x, dp)
    return s[1:] if s.startswith('0.') else s


def sgn(x, dp):
    """带符号定点：-0.0041 / +0.0000。"""
    return '%+.*f' % (dp, float(x))


def cm(x):
    """千分位整数计数。"""
    return '{:,}'.format(int(x))


def env_text(lines):
    return '\n'.join(lines)


# --------------------------------------------------------------------- sources
class Art(object):
    """只读加载 results/** 产物，并按"逐配置算完再对 3 种子平均"的口径提供聚合量。"""

    def __init__(self):
        self.v1 = {}
        for p in sorted(glob.glob(os.path.join(V1D, '*.json'))):
            n = os.path.basename(p)[:-5]
            if n != 'SUMMARY':
                self.v1[n] = json.load(open(p, encoding='utf-8'))
        self.sup = json.load(open(os.path.join(ROOT, 'results', 'phase3_PR1',
                                               'pr1_supplementary.json'),
                                  encoding='utf-8'))['configs']
        self.dsi = json.load(open(os.path.join(ROOT, 'results', 'phase3_PR1',
                                               'pr1_dataset_identity.json'),
                                  encoding='utf-8'))['datasets']
        self.c4 = json.load(open(os.path.join(ROOT, 'results', 'phase1_R1',
                                              'c4_decision_proxy_v2.json'),
                                 encoding='utf-8'))['configs']
        self.cop = json.load(open(os.path.join(ROOT, 'results', 'phase1_R1',
                                               'p08_copulacpts_v2.json'),
                                  encoding='utf-8'))['configs']
        afc = json.load(open(os.path.join(ROOT, 'results', 'phase2_E7',
                                          'author_finding_checks.json'), encoding='utf-8'))
        self.slopes = afc['A1_lambda_slopes']
        self.slope_sign = afc['A1_slope_sign_by_dataset']
        self.c3 = json.load(open(os.path.join(ROOT, 'results', 'phase2_E7',
                                              'cross_config_C3.json'),
                                 encoding='utf-8'))['L4_by_dataset']
        assert len(self.v1) == len(self.sup) == 12, '主实验应有 12 个配置'
        for ds in SUBS:
            for s in SEEDS:
                assert f'{ds}_s{s}' in self.v1 and f'{ds}_s{s}' in self.sup

    # ---- 原子访问
    def cfg(self, ds, seed):
        return f'{ds}_s{seed}'

    def m(self, ds, prog):
        """该子组 3 个配置的 metrics[prog] 节点列表。"""
        return [self.v1[self.cfg(ds, s)]['metrics'][prog] for s in SEEDS]

    def es(self, ds, seed, pair):
        return self.sup[self.cfg(ds, seed)]['effect_sizes'][pair]

    def seg(self, ds, tag):
        ident = self.sup[self.cfg(ds, 42)]['identity']
        return {x['tag']: x for x in ident['segments']}[tag]

    # ---- 聚合量（逐配置算完再平均）
    def path_cov(self, ds, prog):
        return float(np.mean([x['V1']['path_cov'] for x in self.m(ds, prog)]))

    def width_ratio(self, ds, prog):
        return float(np.mean([x['V1']['mean_width'] / y['V1']['mean_width']
                              for x, y in zip(self.m(ds, prog), self.m(ds, 'uncond'))]))

    def grp_cov(self, ds, prog, grp):
        return float(np.mean([x['V1']['group_path_cov'][grp] for x in self.m(ds, prog)]))

    def width_ratio_pair(self, ds, cand, ref):
        return float(np.mean([a['V1']['mean_width'] / b['V1']['mean_width']
                              for a, b in zip(self.m(ds, cand), self.m(ds, ref))]))

    def dcov(self, ds, cand, ref):
        return self.path_cov(ds, cand) - self.path_cov(ds, ref)

    def dg(self, ds, cand, ref, grp):
        return self.grp_cov(ds, cand, grp) - self.grp_cov(ds, ref, grp)

    def cell_cov(self, ds, grouping, cell, prog):
        return float(np.mean([self.sup[self.cfg(ds, s)]['prospective_paths'][grouping]
                              ['cells'][cell][prog]['path_cov'] for s in SEEDS]))

    def cell_width(self, ds, grouping, cell, prog):
        return float(np.mean([self.sup[self.cfg(ds, s)]['prospective_paths'][grouping]
                              ['cells'][cell][prog]['mean_width'] for s in SEEDS]))

    def cell_extremes(self, ds, grouping, prog):
        """gen_tables_pr1::_span 的同一口径：先按种子平均，再在六格上取极值。"""
        v = [self.cell_cov(ds, grouping, c, prog) for c in CELLS]
        return min(v), max(v)

    def cell_extremes_pooled(self, ds, grouping, prog):
        """跨"种子 × 六格"的 18 个逐配置格覆盖率上直接取 min/max。

        收件包 tab:cells 末列（complementary flow grouping 的 range）用的是这个口径，
        与主稿 tab:prospective 的"先按种子平均、再在六格上取极值"不同：
        20 行里两者在 6 行上末位不同，逐字节比对选出的正是本口径。
        """
        v = [self.sup[self.cfg(ds, s)]['prospective_paths'][grouping]
             ['cells'][c][prog]['path_cov'] for s in SEEDS for c in CELLS]
        return min(v), max(v)

    def cell_count(self, ds, cell, prog='uncond'):
        return int(self.sup[self.cfg(ds, 42)]['prospective_paths']['mag']
                   ['cells'][cell][prog]['n_v1_paths'])

    def c4mean(self, ds, thr, meth, field):
        return float(np.mean([self.c4[self.cfg(ds, s)]['thresholds'][thr]
                              ['methods'][meth][field] for s in SEEDS]))


# ------------------------------------------------------------------ 15 张环境
def tab_data(A):
    rows = []
    for ds in ['PEMS03_stae', 'PEMS04_stae', 'PEMS08_stae']:
        te, di = A.seg(ds, 'test'), A.dsi[DSNAME[ds]]
        assert di['nodes'] == te['n_nodes'], f'{ds}: 节点数与身份产物不一致'
        rows.append(f"{NET[ds]} & {cm(di['nodes'])} & {cm(di['time_steps'])} & "
                    f"{cm(te['n_windows'])} & {cm(te['v1_paths'])} & "
                    f"{fx(100 * te['v1_rate'], 2)}\\%\\\\")
    return env_text([r'\begin{tabular}{lrrrrr}', r'\toprule',
                     r'Network & Nodes & Time steps & Test origins & Eligible test paths & Share\\',
                     r'\midrule'] + rows + [r'\bottomrule', r'\end{tabular}'])


def tab_cost(A):
    rows = []
    for disp, m in PROG_COST:
        cells = [f"{lead(A.path_cov(ds, m), 4)} / {lead(A.width_ratio(ds, m), 3)}" for ds in SUBS]
        rows.append(f"{disp} & " + ' & '.join(cells) + r'\\')
    return env_text([r'\begin{tabular}{lcccc}', r'\toprule',
                     r'Program & P03/A & P04/A & P08/A & P08/I\\', r'\midrule']
                    + rows + [r'\bottomrule', r'\end{tabular}'])


def tab_severity(A):
    rows = []
    for ds in SUBS:
        rows.append(f"{SLAB[ds]} & ${sgn(100 * A.dcov(ds, 'g1', 'g0'), 2)}$ & "
                    f"${sgn(100 * A.dg(ds, 'g1', 'g0', 'TypeB'), 2)}$ & "
                    f"${sgn(100 * A.dg(ds, 'g1', 'g0', 'TypeC'), 2)}$ & "
                    f"{fx(A.width_ratio_pair(ds, 'g1', 'g0'), 4)}\\\\")
    return env_text([r'\begin{tabular}{lrrrr}', r'\toprule',
                     r'Subgroup & Overall $\Delta C$ & TypeB $\Delta C$ & TypeC $\Delta C$ '
                     r'& $W_{g_1}/W_{g_0}$\\', r'\midrule'] + rows
                    + [r'\bottomrule', r'\end{tabular}'])


def tab_prospective(A):
    rows = []
    for ds in SUBS:
        cells = []
        for _, m in PROG_PROSP:
            lo, hi = A.cell_extremes(ds, 'mag', m)
            cells.append(f'{lead(lo, 3)}--{lead(hi, 3)}')
        rows.append(f"{SLAB[ds]} & " + ' & '.join(cells) + r'\\')
    return env_text([r'\begin{tabular}{lcccc}', r'\toprule',
                     r'Subgroup & Path maximum & NH & $g_0$ & $g_1$\\', r'\midrule']
                    + rows + [r'\bottomrule', r'\end{tabular}'])


def tab_pop(A):
    rows = []
    for ds, disp in [('PEMS03_stae', 'P03/A'), ('PEMS04_stae', 'P04/A'),
                     ('PEMS08_stae', 'P08/A,I')]:
        if ds == 'PEMS08_stae':                       # 两骨干共用同一数组与时间线
            for fld in ('selection', 'calibration', 'test'):
                assert A.seg('PEMS08_stae', fld)['n_windows'] == \
                    A.seg('PEMS08_stid', fld)['n_windows'], 'PeMS08 两骨干段计数不同'
        se, ca, te = (A.seg(ds, 'selection'), A.seg(ds, 'calibration'), A.seg(ds, 'test'))
        rows.append(f"{disp} & {cm(se['n_windows'])} & {cm(ca['n_windows'])} & "
                    f"{cm(te['n_windows'])} & {cm(ca['v1_paths'])} & {cm(te['v1_paths'])} & "
                    f"{fx(100 * te['v1_rate'], 2)} & {cm(te['nonpositive_elements'])} \\\\")
    return env_text([r'\begin{tabular}{lrrrrrrr}', r'\toprule',
                     r'Subgroup & Sel. origins & Cal. origins & Test origins & Cal. paths '
                     r'& Test paths & Test \% & Excluded\\\midrule']
                    + rows + [r'\bottomrule\end{tabular}'])


def tab_events(A):
    rows = []
    for ds, disp in [('PEMS03_stae', 'PeMS03'), ('PEMS04_stae', 'PeMS04'),
                     ('PEMS08_stae', 'PeMS08')]:
        ec = A.seg(ds, 'test')['event_group_path_counts']
        if ds == 'PEMS08_stae':
            assert ec == A.seg('PEMS08_stid', 'test')['event_group_path_counts'], \
                '事件组计数应与骨干无关'
        tot = sum(ec.values())
        assert tot == A.seg(ds, 'test')['v1_paths'], '事件组未恰好划分 V=1 群体'
        rows.append(f"{disp} & " + ' & '.join(cm(ec[k]) for k in
                                              ('Normal', 'TypeA', 'TypeB', 'TypeC'))
                    + f" & {cm(tot)} \\\\")
    return env_text([r'\begin{tabular}{lrrrrr}', r'\toprule',
                     r'Network & Normal & TypeA & TypeB & TypeC & Total\\\midrule']
                    + rows + [r'\bottomrule\end{tabular}'])


def tab_forecast(A):
    rows = []
    for ds in SUBS:
        for s in SEEDS:
            ident = A.sup[A.cfg(ds, s)]['identity']
            qs, qt = ident['point_quality']['selection'], ident['point_quality']['test']
            tm = ident['provenance'].get('train_meta', {})
            em = ident['provenance'].get('export_meta', {})
            ep = tm.get('epochs_run', tm.get('max_epochs'))
            kept = tm.get('best_epoch', em.get('ckpt_best_epoch'))
            ckpt = tm.get('best_mae', em.get('ckpt_best_mae'))
            assert None not in (ep, kept, ckpt), f'{ds} s{s}: 训练记录缺字段'
            rows.append(f"{SLAB[ds]} & {s} & {fx(qs['MAE_valid_elements'], 2)} & "
                        f"{fx(qt['MAE_valid_elements'], 2)} & "
                        f"{fx(qt['RMSE_valid_elements'], 2)} & "
                        f"{fx(qt['MAE_V1_population'], 2)} & {int(ep)} & {int(kept)} & "
                        f"{fx(ckpt, 2)} \\\\")
    return env_text([r'\begin{tabular}{lrrrrrrrr}', r'\toprule',
                     r'Group & Seed & Sel. MAE & Test MAE & RMSE & V1 MAE & Epochs & Kept '
                     r'& Ckpt. MAE\\\midrule'] + rows + [r'\bottomrule\end{tabular}'])


def tab_effects(A):
    head = r'Group & Seed & Contrast & $\Delta C$ & 95\% interval & L95 & $R_W$ & U95 & G1/G2'
    rows = []
    for ds in SUBS:
        for s in SEEDS:
            for disp, pair in CONTRASTS:
                e = A.es(ds, s, pair)
                ci = e['delta_CI95_two_sided']
                rows.append(f"{SLAB[ds]} & {s} & {disp} & "
                            f"{sgn(e['delta_coverage_point_estimate'], 4)} & "
                            f"[{sgn(ci[0], 4)},{sgn(ci[1], 4)}] & "
                            f"{sgn(e['delta_one_sided_lower_p5'], 4)} & "
                            f"{fx(e['width_ratio_point_estimate'], 4)} & "
                            f"{fx(e['ratio_one_sided_upper_p95'], 4)} & "
                            f"{'P' if e['G1_pass'] else 'F'}/{'P' if e['G2_pass'] else 'F'} \\\\")
    assert len(rows) == 36
    return env_text([r'\begin{longtable}{lllrcrrrc}',
                     r'\caption{Configuration-level paired effects. The coverage interval is '
                     r'two-sided 95\%; L95 and U95 are the separate one-sided bounds used by G1 '
                     r'and G2. For NH/path, the candidate is NH; other comparisons use g1.}'
                     r'\label{tab:effects}\\',
                     r'\toprule', head + r'\\\midrule', r'\endfirsthead',
                     r'\toprule', head + r'\\\midrule', r'\endhead',
                     r'\bottomrule\endfoot'] + rows + [r'\end{longtable}'])


def tab_cells(A):
    head = (r'Group & Program & 0/T1 & 0/T2 & 0/T3 & 1/T1 & 1/T2 & 1/T3 & Flow range')
    rows = []
    for ds in SUBS:
        for disp, m in PROG_CELL:
            cells = [f"{fx(A.cell_cov(ds, 'mag', c, m), 3)}/"
                     f"{fx(A.cell_width(ds, 'mag', c, m), 0)}" for c in CELLS]
            lo, hi = (A.cell_extremes(ds, 'flow', m) if FLOW_RANGE == 'seed_mean'
                      else A.cell_extremes_pooled(ds, 'flow', m))
            rows.append(f"{SLAB[ds]} & {disp} & " + ' & '.join(cells)
                        + f" & {lead(lo, 2)}--{lead(hi, 2)} \\\\")
    assert len(rows) == 20
    return env_text([r'\begin{longtable}{llccccccc}',
                     r'\caption{Path coverage / mean full width in flow units in the six '
                     r'predicted-magnitude cells. Columns 0/T1--0/T3 have no input transition; '
                     r'1/T1--1/T3 have an input transition. Cells and widths are three-seed '
                     r'means; widths retain integer rounding. The last column is the range of '
                     r'the same three-seed mean cell coverages under the complementary flow '
                     r'grouping.}\label{tab:cells}\\',
                     r'\toprule', head + r'\\\midrule', r'\endfirsthead',
                     r'\toprule', head + r'\\\midrule', r'\endhead',
                     r'\bottomrule\endfoot'] + rows + [r'\end{longtable}'])


def tab_cellcounts(A):
    rows = []
    for ds in SUBS:
        ns = [A.cell_count(ds, c) for c in CELLS]
        ref = A.seg(ds, 'test')['v1_paths']
        assert sum(ns) == ref, f'{ds} s42: 六格未恰好划分该种子的完整路径群体'
        rows.append(f"{SLAB[ds]} & " + ' & '.join(cm(n) for n in ns) + r' \\')
    return env_text([r'\begin{tabular}{lrrrrrr}', r'\toprule',
                     r'Group & 0/T1 & 0/T2 & 0/T3 & 1/T1 & 1/T2 & 1/T3\\\midrule']
                    + rows + [r'\bottomrule\end{tabular}'])


def tab_support(A):
    allc = [A.sup[A.cfg(ds, s)] for ds in SUBS for s in SEEDS]
    assert len(allc) == 12
    rows = []
    for disp, m in PROG_SUPP:
        w = float(np.mean([c['support_clip'][m]['mean_width_original'] for c in allc]))
        wc = float(np.mean([c['support_clip'][m]['mean_width_clipped'] for c in allc]))
        red = [c['support_clip'][m]['width_reduction_pct'] for c in allc]
        neg = [100 * c['support_clip'][m]['frac_lower_below_zero'] for c in allc]
        ro = float(np.mean([c['support_clip'][m]['mean_width_original']
                            / c['support_clip']['uncond']['mean_width_original'] for c in allc]))
        rc = float(np.mean([c['support_clip'][m]['mean_width_clipped']
                            / c['support_clip']['uncond']['mean_width_clipped'] for c in allc]))
        assert all(c['support_clip'][m]['element_hits_unchanged']
                   and c['support_clip'][m]['path_hits_unchanged'] for c in allc)
        rows.append(f"{disp} & {fx(w, 1)} & {fx(wc, 1)} & {fx(min(red), 2)}--{fx(max(red), 2)} & "
                    f"{fx(min(neg), 1)}--{fx(max(neg), 1)} & {fx(ro, 3)} & {fx(rc, 3)} \\\\")
    return env_text([r'\begin{tabular}{lrrccrr}', r'\toprule',
                     r'Program & W & W+ & Reduction (\%) & $\ell<0$ (\%) & Ratio & Ratio+'
                     r'\\\midrule'] + rows + [r'\bottomrule\end{tabular}'])


def tab_rules(A):
    rows = []
    for ds in SUBS:
        rows.append(f"{SLAB[ds]} & {sgn(A.dg(ds, 'sev', 'uncond', 'TypeC'), 4)} & "
                    f"{sgn(A.dg(ds, 'sev', 'uncond', 'TypeB'), 4)} & "
                    f"{sgn(A.dg(ds, 'g1', 'g0', 'TypeC'), 4)} & "
                    f"{sgn(A.dg(ds, 'g1', 'g0', 'TypeB'), 4)} & "
                    f"{fx(A.width_ratio_pair(ds, 'g1', 'g0'), 4)} \\\\")
    return env_text([r'\begin{tabular}{lrrrrr}', r'\toprule',
                     r'Group & Swap TypeC & Swap TypeB & $g_1-g_0$ TypeC & $g_1-g_0$ TypeB '
                     r'& $W_{g_1}/W_{g_0}$\\\midrule'] + rows
                    + [r'\bottomrule\end{tabular}'])


def tab_sweep(A):
    rows = []
    for ds, field, disp in SWEEP_ROWS:
        net = SHORTNET[ds]
        st = A.slope_sign[f'{DSNAME[ds]}/{field}']
        ex = A.slopes[A.cfg(ds, 42)][field]['d_path_cov_0to1']
        ratio = A.c3[DSNAME[ds]]['drift_mean']
        assert st['n'] == st['n_negative'] + st['n_positive']
        assert st['n_negative'] == sum(1 for v in st['slopes'] if v < 0)
        assert st['n_positive'] == sum(1 for v in st['slopes'] if v > 0)
        rows.append(f"{net} & {disp} & {st['n']} & {st['n_negative']} & {st['n_positive']} & "
                    f"{sgn(ex, 4)} & {fx(ratio, 3)} \\\\")
    return env_text([r'\begin{tabular}{llrrrcr}', r'\toprule',
                     r'Network & Field & Curves & Negative & Positive & Example $\Delta C$ '
                     r'& Scale ratio\\\midrule'] + rows + [r'\bottomrule\end{tabular}'])


def tab_copula(A):
    rows = []
    for ds, s in COP_ROWS:
        for disp, v1prog, copkey in COP_PROG:
            if copkey is None:
                node = A.v1[A.cfg(ds, s)]['metrics'][v1prog]['V1']
            else:
                ck = f"{DSNAME[ds]}_s{s}"
                assert ck in A.cop, f'Copula 产物缺少 {ck}'
                node = A.cop[ck][copkey]['V1']
            rows.append(f"{SLAB[ds]} & {s} & {disp} & {fx(node['path_cov'], 4)} & "
                        f"{fx(node['mean_width'], 1)} & {fx(node['IS'], 1)} \\\\")
    assert len(rows) == 20
    return env_text([r'\begin{longtable}{lllr rr}',
                     r'\caption{Feasible CopulaCPTS comparison on development configurations '
                     r'only. Copula+NH includes the additional static normalization. All widths '
                     r'and interval scores use V=1. The more conservative and differently '
                     r'covered operating points are not an equal-coverage comparison.}'
                     r'\label{tab:copula}\\',
                     r'\toprule',
                     r'Group & Seed & Program & Path coverage & Width & IS\\\midrule',
                     r'\endfirsthead',
                     r'\toprule',
                     r'Group & Seed & Program & Path coverage & Width & IS\\\midrule',
                     r'\endhead', r'\bottomrule\endfoot'] + rows + [r'\end{longtable}'])


def tab_decision(A):
    head = (r'Threshold & Group & Program & $P(S)$ & $P(A\cap S)$ & $P(A\mid S)$ '
            r'& Peak exceed.')
    rows = []
    for thr, disp in [('Q0.99', '99'), ('Q0.95', '95')]:
        for ds in DEC_GROUPS:
            for pdisp, meth in DEC_PROG:
                ps = A.c4mean(ds, thr, meth, 'P_S')
                pas = A.c4mean(ds, thr, meth, 'P_A_and_S')
                pg = A.c4mean(ds, thr, meth, 'P_A_given_S')
                pk = A.c4mean(ds, thr, meth, 'peak_exceedance_V1')
                rows.append(f"{disp} & {SLAB[ds]} & {pdisp} & {lead(ps, 3)} & {lead(pas, 4)} & "
                            f"{lead(pg, 4)} & {lead(pk, 3)} \\\\")
    assert len(rows) == 32
    return env_text([r'\begin{longtable}{llllrrr}',
                     r'\caption{Certification availability, joint error and conditional error. '
                     r'Each entry is a mean of configuration-level probabilities. Because '
                     r'averaging and division do not commute, multiplying two rounded mean '
                     r'columns need not recover the third exactly. Peak exceedance is observed '
                     r'on Test, not fixed to 0.10 by construction.}\label{tab:decision}\\',
                     r'\toprule', head + r'\\\midrule', r'\endfirsthead',
                     r'\toprule', head + r'\\\midrule', r'\endhead',
                     r'\bottomrule\endfoot'] + rows + [r'\end{longtable}'])


BUILDERS = [('tab:data', tab_data), ('tab:cost', tab_cost), ('tab:severity', tab_severity),
            ('tab:prospective', tab_prospective), ('tab:pop', tab_pop),
            ('tab:events', tab_events), ('tab:forecast', tab_forecast),
            ('tab:effects', tab_effects), ('tab:cells', tab_cells),
            ('tab:cellcounts', tab_cellcounts), ('tab:support', tab_support),
            ('tab:rules', tab_rules), ('tab:sweep', tab_sweep), ('tab:copula', tab_copula),
            ('tab:decision', tab_decision)]


def build_all(A):
    out = {}
    for lab, fn in BUILDERS:
        txt = fn(A)
        assert '\t' not in txt, f'{lab}: 生成环境含制表符'
        nb = txt.count(r'\begin{tabular}') + txt.count(r'\begin{longtable}')
        ne = txt.count(r'\end{tabular}') + txt.count(r'\end{longtable}')
        assert nb == ne == 1, f'{lab}: 表格环境应恰好一个，实得 begin={nb} end={ne}'
        assert txt.startswith(r'\begin{') and (
            txt.endswith(r'\end{tabular}') or txt.endswith(r'\end{longtable}')), \
            f'{lab}: 环境首尾不是 \\begin/\\end'
        assert txt.count('{') == txt.count('}'), f'{lab}: 花括号不闭合'
        out[lab] = txt
    assert len(out) == 15
    return out


def written_name(lab):
    return 'tab_' + lab.split(':')[1] + '.tex'


def input_path(lab):
    return 'generated/' + 'tab_' + lab.split(':')[1]


# ------------------------------------------------------- 收件包环境的提取
ENV_RE = re.compile(r'\\begin\{(tabular|longtable)\}')


def received_envs():
    """{label: (src_key, 环境本体)}，按收件包源文件逐字节切出。"""
    out = {}
    for key in ('main', 'supp'):
        t = open(SRC[key], encoding='utf-8').read()
        for m in ENV_RE.finditer(t):
            env = m.group(1)
            close = '\\end{' + env + '}'
            e = t.index(close, m.start()) + len(close)
            txt = t[m.start():e]
            lab = re.search(r'\\label\{(tab:[a-z]+)\}', txt)
            if lab:
                lab = lab.group(1)
            else:
                prev = re.findall(r'\\label\{(tab:[a-z]+)\}', t[:m.start()])
                lab = prev[-1]
            assert lab not in out, f'{lab} 出现两次'
            out[lab] = (key, txt)
    assert len(out) == 15, f'收件包应有 15 个表格环境，实得 {len(out)}'
    return out


def only_last_col_diff(recv_env, gen_env):
    """登记偏离的唯一允许形状：逐行比较，差异只落在数据行的**最后一列**。

    返回 (是否合法, [(行号, 收件值, 生成值), ...])。
    """
    rl, gl = recv_env.split('\n'), gen_env.split('\n')
    if len(rl) != len(gl):
        return False, [('line-count', len(rl), len(gl))]
    diffs, cap_seen = [], 0
    for i, (a, b) in enumerate(zip(rl, gl)):
        if a == b:
            continue
        if '\\caption{' in a and '\\caption{' in b:
            # 只允许改图注文字：改动处不得含数字，且题注外的部分必须逐字相同
            k = next((j for j in range(min(len(a), len(b))) if a[j] != b[j]), None)
            if k is None or '\\caption{' not in a[:k]:
                return False, [(i, 'caption-prefix', '')]
            if re.search(r'\d', a[k:]) or re.search(r'\d', b[k:]):
                return False, [(i, 'caption-touches-a-number', '')]
            cap_seen += 1
            continue
        ca, cb = a.split(' & '), b.split(' & ')
        if len(ca) != len(cb) or ca[:-1] != cb[:-1] or not ca[-1].endswith('\\\\'):
            return False, [(i, a, b)]
        diffs.append((i, ca[-1], cb[-1]))
    return cap_seen <= 1, diffs


def working_copy(envs):
    """把收件包两份源里的表格环境替换成 \\input 行，其余字节不变。"""
    out = {}
    fixed = {}
    for key, path in SRC.items():
        t = open(path, encoding='utf-8').read()
        pieces, pos = [], 0
        for m in ENV_RE.finditer(t):
            env = m.group(1)
            close = '\\end{' + env + '}'
            e = t.index(close, m.start()) + len(close)
            lab = re.search(r'\\label\{(tab:[a-z]+)\}', t[m.start():e])
            if lab:
                lab = lab.group(1)
            else:
                lab = re.findall(r'\\label\{(tab:[a-z]+)\}', t[:m.start()])[-1]
            want = t[m.start():e]
            if lab in KNOWN_DEV:
                ok, _ = only_last_col_diff(want, envs[lab])
                assert ok, f'{lab}: 偏离超出登记的 flow-range 末列，拒绝替换'
            else:
                assert want == envs[lab], f'{lab} 与生成环境不一致，拒绝替换'
            pieces.append(t[pos:m.start()])
            pieces.append('\\input{' + input_path(lab) + '}')
            pos = e
        pieces.append(t[pos:])
        s = ''.join(pieces)
        for old, new in TEXT_FIXES:
            n = s.count(old)
            assert n in (0, 1), f'TEXT_FIXES 目标在 {key} 内出现 {n} 次'
            fixed[key] = fixed.get(key, 0) + n
            s = s.replace(old, new)
        out[key] = s
    assert sum(fixed.values()) == len(TEXT_FIXES), \
        f'登记的文字修正未全部命中: {fixed}'
    return out


# ------------------------------------------------------------------------- IO
def emit(envs, dest):
    os.makedirs(dest, exist_ok=True)
    for lab, txt in envs.items():
        fn = os.path.join(dest, written_name(lab))
        with open(fn, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(HDR + '\n' + txt + '\n')
    return sorted(envs)


def do_write(A, envs):
    emit(envs, GEN)
    wc = working_copy(envs)
    with open(os.path.join(OUT, 'main.tex'), 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(wc['main'])
    with open(os.path.join(OUT, 'supplement.tex'), 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(wc['supp'])
    for fn in ('references.bib', 'main.bbl'):
        shutil.copyfile(os.path.join(PKG, 'manuscript', fn), os.path.join(OUT, fn))
    print(f'已写出 {len(envs)} 个生成表 -> '
          + os.path.relpath(GEN, ROOT).replace(os.sep, '/'))
    print('已写出工作副本 -> paper/condensed/{main.tex, supplement.tex}，'
          '并复制 manuscript/{references.bib, main.bbl}')


def do_check(A, envs):
    rec = received_envs()
    tmp = tempfile.mkdtemp(prefix='pr2check_')
    try:
        emit(envs, tmp)
        rows, bad = [], 0
        for lab, _fn in BUILDERS:
            src, want = rec[lab]
            got = open(os.path.join(tmp, written_name(lab)), encoding='utf-8').read()
            status = 'PASS'
            if got != HDR + '\n' + want + '\n':
                legal, diffs = only_last_col_diff(want, envs[lab])
                if lab in KNOWN_DEV and legal:
                    status = f'DEVIATION-REGISTERED ({len(diffs)} cells)'
                    for i, old, new in diffs:
                        print(f'    {lab} 行{i}: 收件 {old}  ->  本地 {new}')
                else:
                    status = 'FAIL'
                    bad += 1
                    print(f'    {lab}: 与收件包不一致且不在登记偏离内')
            rows.append((lab, written_name(lab), os.path.basename(SRC[src]),
                         len(want.encode('utf-8')), status))
        print('  %-15s %-22s %-16s %8s  %s'
              % ('label', 'generated file', 'received source', 'bytes', 'status'))
        n_pass = sum(1 for r in rows if r[4] == 'PASS')
        for lab, fn, src, nb, status in rows:
            print('  %-15s %-22s %-16s %8d  %s' % (lab, fn, src, nb, status))
        print('--check: %d/%d 环境与收件包逐字节一致，其余为已登记偏离或 FAIL'
              % (n_pass, len(rows)))

        # 附加自检：工作副本与 generated/ 落盘内容也必须是本脚本的产物
        wc = working_copy(envs)
        extra = []
        for key, fn in (('main', 'main.tex'), ('supp', 'supplement.tex')):
            p = os.path.join(OUT, fn)
            have = open(p, encoding='utf-8').read() if os.path.exists(p) else None
            ok = have == wc[key]
            # 反向替换：把 \\input 行还原成收件包环境本体，必须与收件包源逐字节相同，
            # 这才能证明"除 15 处替换外没有其他任何字节变化"。
            back = have or ''
            for lab, (k, env) in rec.items():
                if k == key:
                    tok = '\\input{' + input_path(lab) + '}'
                    assert back.count(tok) == 1, f'{fn}: 缺少唯一的 {tok}'
                    back = back.replace(tok, env, 1)
            for old, new in TEXT_FIXES:          # 还原登记的文字修正
                back = back.replace(new, old)
            ident = back == open(SRC[key], encoding='utf-8').read()
            extra.append(ok and ident)
            print(f'  working copy {fn:<16} 与替换结果一致: '
                  + ('PASS' if ok else 'FAIL')
                  + ' | 还原 15 处 \\input 与登记文字修正后与收件包源逐字节相同: '
                  + ('PASS' if ident else 'FAIL'))
        disk = True
        for lab, _fn in BUILDERS:
            p = os.path.join(GEN, written_name(lab))
            txt = open(p, encoding='utf-8').read() if os.path.exists(p) else None
            disk = disk and txt == HDR + '\n' + envs[lab] + '\n'
        extra.append(disk)
        print('  paper/condensed/generated/ 落盘内容与本次重建一致: '
              + ('PASS' if disk else 'FAIL'))
        return 0 if bad == 0 and all(extra) else 1
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def do_out(A, envs, out_dir):
    """--out 模式：只把 15 张生成表写到 <out_dir>/generated/。

    供 PR3 合并稿基线 paper/integrated/ 复用同一条
    `results/**.json -> 生成器 -> generated/*.tex -> \\input` 通道；
    该基线的 main.tex/supplement.tex/references.bib/main.bbl 直接取自收件包
    （逐字节相同），故本模式不写工作副本、不复制 bib/bbl。
    """
    gen = os.path.join(out_dir, 'generated')
    emit(envs, gen)
    try:
        rel = os.path.relpath(gen, ROOT).replace(os.sep, '/')
    except ValueError:                              # 跨盘等情形，直接给绝对路径
        rel = gen
    print(f'已写出 {len(envs)} 个生成表 -> {rel}')


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--check', action='store_true',
                    help='只校验：重建到临时目录并与收件包环境逐字节比对，不写任何文件')
    ap.add_argument('--out', default=None, metavar='DIR',
                    help='只把 15 张生成表写到 DIR/generated/（默认：写 paper/condensed 完整工作副本）')
    args = ap.parse_args()
    A = Art()
    envs = build_all(A)
    if args.check:
        return do_check(A, envs)
    if args.out:
        do_out(A, envs, os.path.abspath(args.out))
        return 0
    do_write(A, envs)
    return 0


if __name__ == '__main__':
    sys.exit(main())
